app.upload-dir=uploads

spring.datasource.url=jdbc:postgresqgl://localhost:5432/edm
spring.datasource.username=edm
spring.datasource.password=edm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

